language: python
python:
- '3.6'
services: docker
git:
  depth: false
install: make build
stages:
- name: test
- name: publish-release
  if: branch = master AND type != pull_request
- name: publish-staging
  if: branch != master AND type != pull_request
jobs:
  include:
  - stage: test
    name: Test Docker
    script:
    - make version print-pypi
    - make test-docker
  - stage: publish-staging
    name: Publish staging image
    script:
    - docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
    - make publish-staging
  - stage: publish-release
    name: Publish production image
    script:
    - docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
    - make publish-release
env:
  global:
  - BRANCH_NAME=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - secure: DB+cWZGiD7w86ocJ287wuEVEc2wcB/9W2VxcTvyIQiGIMJFNMGY0iHUHa6tAY6xZPELQK3/lM1yaoLEFbfxPwYydcwfKyIr5+SpQlaA3XiPSUnI8v1Z9ocDdRIM3DYl7NdM+QziesDvRgoBGGRbkQ+5YM/rOyo/4/cR7Zr1pmk72Oa7YMRbGYRTEeJD/4flcTYqqLBkQK6Aq54aTvkcCfpqp7USyV+Y7tkbiv9rHyqENSW5dXpH1oTeY0RIYPnoZN88279IRfbQ7ZKZi7Djt0BfTGazdenBEs3cyG3LENy/IubGnU8XMLVzaWgkzqyr/Ui0ZZVHcJT+8DrHavXTGNPZaGbZpeQGSCD59K3jK3aqAZRHqyvEapZxfx/CrkYbFnjzRfA5KYxElZGTQUrmiX4yDVb6/JSZRfFLnwWxVaGuAtL2CSUNiNdS/eCWr/2zpco3R+tOkqodf/vleyZJLtcxW2mvCMiMbQoY5Xm6M1EWOk/hip2X6VxwIM2c53+y+OTCBgDAirsOhVCqR6103GR/0l+MJrFXl9nBZvqgzPcGVy2Dl9FFxhmfi3GMRZArPrK1uStoN/vFV25w/yfp25N5fc/89cW/dkYJ23rcWht+KCOu0IFUAbyDRsmI6V0JAs8Zren+lUtuqM7YtiRRl+x57bGUhbAzipHpXgB3Mi04=
  - secure: s+Aa5myhcIIfZHqtu75SAQaI9X8brb4wAEmTrQBWcC9giNPT6DnL/XpEpE4y3VtxmjAJO4OBORGV2lF8qsir9Pe4Zk3MuqL2XB0HPtPS+DWcn5ws3HoG5u3/jg+A//vysFOGZ1+nnVbQdtuj23mqqzehDYuSb6zdObMOwMN+Ed0Ub0KngRYPFIvOff8xp21B/+1KxvA//ZMBgokU4jqisydgrgLkBEc2QDN0JyRzgadp7KsUZhU2OoD61a2Jmi+GjtUxkaT7XXFvSw4JmwdVUze7YHy5qx5Qln/olmKx5o96hSNh906elDMO9juf08dGd/+kw5NHNp6faKGFoDl4YtDDPerV8z5RdtCbh8obBukj30jlvYOw6t5W3uih1Esr1u5klgy4F8U8yo40KEGuULfV0B7foMk4pyEY3x+TVmc/AlqPTSWKzTxOEP3yVncL/0rfXbkQ2Sh064YElR4FH2rTnTOrWbpYg6Q1RyG3fAedZ17d+NPpDkb/Vty+U2+FiGrRRczpJH9N12RYpPHAjtzuQedbWVK5skkqtaVyEnIBdLX2G+xi3WuU+qRh9hoRse6biylfNbSU/O8rmb4gmfkLDf6VqnMRC4JJJa+MguyeY2nRMWC8YItRaffCYx6mOIrm80xpkZ2BxnSDyRMtwdS19yjXfixjXoObqyShnMk=
