language: python
python:
- '3.6'
services: docker
git:
  depth: false
install: make build
stages:
- name: test
- name: publish-release
  if: branch = master AND type != pull_request
- name: publish-staging
  if: branch != master AND type != pull_request
jobs:
  include:
  - stage: test
    name: Test Docker
    script:
    - make version print-pypi
    - make test-docker
  - stage: publish-staging
    name: Publish staging image
    script:
    - docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
    - make publish-staging
  - stage: publish-release
    name: Publish production image
    script:
    - docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
    - make publish-release
env:
  global:
  - BRANCH_NAME=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - secure: BE+ULJsn8pAVoYW2xbDn8GCB4G7gqlcwmiPlwQ3tke5DIWh1goFPQ3STGcWUxnKXGJxxKSwcfa3OAthxv6HcfLzlNXGggBU+JMAuRDlxzGprUyHeoLG8mjFvmQZZmZsIPgG5rm4KtEl9nopBpdz6TXrUdd3O9+zJQkShEEzJ3S9rUvMhW8i8OwSeDDrnq79Nm8hhMq+n0uu+OO/58x6Nan7EBlRpoA6VeZOdSV2ov5zpFN4Sh00HiGM62dk11idaR0wu5S02V7c02bguyAL5zKhZ7ZF5Uw9BCnA5TRnnpWSDGFr6QKfTZfv07WfXb4Gz8/BKsMWFAjhX/cuAcr4dTDnj1UGuiM4meL/GqGIeELg9HUszxAEJ7n9I885jP+kriMVfW5GJk5M8Me30dzCcgdBSEr+MsCIzdFzeLOIgfpLoStrD+ECzcfKf9bHAnTdkUpKvkO03iP/5sU1fy6yilzrO9bF1jTLMOKLiqMtsB8rgnxVYY/hpK9ZDx923dboZ4c4N/JZ+uZwhO7a6Tulm3mMe3+XH8G0GeuYCgUd8vZepDTek7d3+bDFrmtFWAeA2P6OZi5v8lKA0JHEh8nQL/nD88fXXS3UID2vtTeyyExBmyUzZQTDtvvN489NsJtf/8iNNxQF96m90A6ipxmOYl/vdb1x75rezEUwgWxgaCyc=
  - secure: GU3ezx3IaqI6v4zF0QuyxyopARsICjhB8ni2553Mnm+SyV31MbwvPghr0cuXI/buQUV+bAUCOKupbG6pK2V22Am6uXPBvfRybpanCo6Hgrll20KenOh0eTYNrc8n8NqTWPvBy3JUtyu8mbR5DcHvL9OzleWaj0URcwWxV1YWtynulPSBYzx4JZLvKfepM51FjAuSE3BcnY3BzD9ogeaujtN91HZ4Q/H1gMzF7+9Lj9ikAzAlB63ZShJDlbBW1T8v+67PtO94CvU8d8B9sBVjiaQFoNxQkhRhsByX3rtFEc5K8QprJ/TESnIJZA3kttSHVpQUzXethBu/0ep5wTZL/5H8tjm91XxaMM1ZMU4BE7bY+7HDrLr2WJpnifDFD4DTWxGmng/WT6k0WazXMCICHBEC83IkxQslkEMNl/THQ0sVZ6fUSBQM/Zfoy+DySeAWvXYOyUw3VMNEl1BYY0jfOFjwD93I5jGTCDSvgpxEJgDYdqFQe7GOEh+7Bs7UY6v1r0pL0AakIOLeu59Yqtkiueh+v2jsKuVlZTL1LOS6h1ilb0rl2AX1szIZpw7540X3oVPezgepjyg+xWZXLtY0auy/RuKxICB5LLFlDzLgVnZ4WT+M96ol5A/IO/+Tc/Mh+FQ29g4zhIHJxKJi2g+iO7sdaFhUGhluBuVJWlxLQRM=
